name: Mac Installer

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: dotnet nuget locals all --clear

      - run: dotnet restore MyApp/MyApp.csproj

      - run: dotnet publish MyApp/MyApp.csproj -c Release -r osx-arm64 --self-contained true -p:UseAppHost=true -p:PublishSingleFile=false

      - run: find . -name "*.app"

      - run: mkdir dmg

      - run: cp -R **/*.app dmg/

      - run: brew install create-dmg

      - run: |
          create-dmg \
            --volname "SimplyGreatTimer" \
            --window-pos 200 120 \
            --window-size 600 350 \
            --icon-size 100 \
            --app-drop-link 450 150 \
            SimplyGreatTimer-MacOS-Install.dmg \
            dmg/

      - uses: softprops/action-gh-release@v2
        with:
          files: SimplyGreatTimer-MacOS-Install.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}