name: Mac Installer

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - run: dotnet nuget locals all --clear

      - run: dotnet restore MyApp/MyApp.csproj

      - run: |
          dotnet publish MyApp/MyApp.csproj \
            -c Release \
            -r osx-arm64 \
            --self-contained true \
            -p:UseAppHost=true \
            -p:PublishSingleFile=false \
            -o publish

      - run: ls -R publish

      - run: chmod -R +x publish || true

      - run: mkdir dmg

      - run: cp -R publish/. dmg/

      - run: brew install create-dmg

      - run: |
          create-dmg \
            --volname "SimplyGreatTimer" \
            --window-size 700 400 \
            SimplyGreatTimer-MacOS-Install.dmg \
            dmg/

      - uses: softprops/action-gh-release@v2
        with:
          files: SimplyGreatTimer-MacOS-Install.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}