name: Windows Installer

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: dotnet restore MyApp/MyApp.csproj

      - run: dotnet publish MyApp/MyApp.csproj -c Release -r win-x64 --self-contained true -o publish

      - run: choco install innosetup -y

      - run: iscc installer.iss

      - run: dir Output

      - uses: softprops/action-gh-release@v2
        with:
          files: Output/SimplyGreatTimer-Windows-Install.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
